### ISSUE TITLE
Sound no longer works

### ISSUE THREAD

**Issue by Kippykip** [z2442/sm64-port#24]
It seems after building and running on an actual PSP, only the music on the title screen plays but there's no sound for the rest of the game.
Do I have to do something dodgy with **snd_eng.prx** like load it as a plugin or something? Right now I've just got it in the same folder as the EBOOT.PBP

**Comment by Kippykip** [comment]
Ok update, now sound is playing for some reason? But later on in some levels some mario sound effects stop working midway through the level, plus the bomb bossfight seems to not play the boss theme music properly but plays high pitch sound instead.
kinda weird

**Comment by TheMrIron2** [comment]
Sound generation on the Media Engine is not very stable right now, known issue being worked on. See if switching sound generation to CPU (square + R?) resolves your issues, as this should be more stable.

**Comment by Kippykip** [comment]
Ah yep! That did the trick! Although tanks the FPS understandably. 
This port is pretty awesome though so far, I'd love to see how this goes for the remainder of the year.
Great work!
