### ISSUE TITLE
Build Questions

### ISSUE THREAD

**Issue by scoronado12** [z2442/sm64-port#8]
Hi z2442, I am currently reworking the present `Dockerfile` to build the eboot executable within a container since for some reason I can not get those PSP libraries installed on my Arch system using the package manager. The goal is to do the following:

- Build Container
- Unpack PSP Libs and dependencies
- switch to a copy of this repo
- run `make TARGET_PSP=1`
- copy EBOOT.PBP back to the host
- Stop running container

My question for you is where are you placing the Eboot file once `make` completes? Is it in `psp/EBOOT`? I wanted to ask just in case. You seem to have not reflected this change in your Readme.

**Comment by mrneo240** [comment]
sorry, i added the pbp stuff quickly since it isnt useful for non devs.
it builds currently in ``build/us_psp/mario64/EBOOT.pbp``

**Comment by scoronado12** [comment]
All good. This is something I've been playing with in my free time so it's nothing urgent.
